monolog:
    handlers:
        main:
            type :          stream
            path:           "%kernel.logs_dir%/%kernel.environment%.all.log"
            buffer_size:    1000
            level:          info
        streamed:
            type: rotating_file
            max_files : 15
            path: "%kernel.logs_dir%/%kernel.environment%.error.log"
            level: error

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
