admin:
  resource: '../src/Controller/Admin'
  type: annotation
  prefix: '/admin'

api_editor:
  resource: '../src/Controller/API/Editor'
  type: attribute
  prefix: '/api/editor'

cms:
  resource: .
  type: cms
