admin:
  resource: '../src/Controller/Admin'
  type: attribute
  prefix: '/admin'

api_editor:
  resource: '../src/Controller/API'
  type: attribute
  prefix: '/api'

app:
  resource: '../src/Controller/App'
  type: attribute

cms:
  resource: .
  type: cms
  defaults:
    schemes: [ https ]
